// <auto-generated />
namespace DaddyAgencies.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class incepotion_postal_code : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(incepotion_postal_code));
        
        string IMigrationMetadata.Id
        {
            get { return "201903071117433_incepotion_postal_code"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
