// <auto-generated />
namespace DaddyAgencies.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class remove_reuqire_inseption_user : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_reuqire_inseption_user));
        
        string IMigrationMetadata.Id
        {
            get { return "201902051940281_remove_reuqire_inseption_user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
