//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaddyAgencies.Common.Util.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DaddyAgencies.Common.Util.Resources.UI", typeof(UI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confiez-nous votre bien immobilier !.
        /// </summary>
        public static string AddPropertyButton {
            get {
                return ResourceManager.GetString("AddPropertyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendez votre bien.
        /// </summary>
        public static string AddPropertyButtonMin {
            get {
                return ResourceManager.GetString("AddPropertyButtonMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse:.
        /// </summary>
        public static string AddressFormLabel {
            get {
                return ResourceManager.GetString("AddressFormLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panneau de gestion.
        /// </summary>
        public static string AdminPanel {
            get {
                return ResourceManager.GetString("AdminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _More.
        /// </summary>
        public static string AdvancedSearchButton {
            get {
                return ResourceManager.GetString("AdvancedSearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Papa Fait Le Buzz.
        /// </summary>
        public static string BuzzPage {
            get {
                return ResourceManager.GetString("BuzzPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne peux pas être vide.
        /// </summary>
        public static string CannotBeEmpty {
            get {
                return ResourceManager.GetString("CannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modifier.
        /// </summary>
        public static string CardEditLink {
            get {
                return ResourceManager.GetString("CardEditLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to actualiser.
        /// </summary>
        public static string CardRefreshLink {
            get {
                return ResourceManager.GetString("CardRefreshLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cette page.
        /// </summary>
        public static string CardToPageLink {
            get {
                return ResourceManager.GetString("CardToPageLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string ConfirmationSectionTitle {
            get {
                return ResourceManager.GetString("ConfirmationSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse confirmée:.
        /// </summary>
        public static string ConfirmedAddressFormLabel {
            get {
                return ResourceManager.GetString("ConfirmedAddressFormLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date confirmée:.
        /// </summary>
        public static string ConfirmedDateFormLabel {
            get {
                return ResourceManager.GetString("ConfirmedDateFormLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe confirmée:.
        /// </summary>
        public static string ConfirmPasswordFormLabel {
            get {
                return ResourceManager.GetString("ConfirmPasswordFormLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le mot de passe ne correspond pas.
        /// </summary>
        public static string ConfirmPasswordFormPlaceholder {
            get {
                return ResourceManager.GetString("ConfirmPasswordFormPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 Heures Credit.
        /// </summary>
        public static string CreditPage {
            get {
                return ResourceManager.GetString("CreditPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string CustomerSectionTitle {
            get {
                return ResourceManager.GetString("CustomerSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de naissance .
        /// </summary>
        public static string DateOfBirthFormLabel {
            get {
                return ResourceManager.GetString("DateOfBirthFormLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La description:.
        /// </summary>
        public static string DescriptionFormLabel {
            get {
                return ResourceManager.GetString("DescriptionFormLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string EmailFormLabel {
            get {
                return ResourceManager.GetString("EmailFormLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to example@mail.com.
        /// </summary>
        public static string EmailFormPlaceholder {
            get {
                return ResourceManager.GetString("EmailFormPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favoris.
        /// </summary>
        public static string FavoriteCardLink {
            get {
                return ResourceManager.GetString("FavoriteCardLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , selectionez votre bien et clickez sur &quot;etoile&quot;.
        /// </summary>
        public static string FavoriteCardsEmptyTextAfter {
            get {
                return ResourceManager.GetString("FavoriteCardsEmptyTextAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajoutez au favoris.
        /// </summary>
        public static string FavoriteCardsEmptyTextBefore {
            get {
                return ResourceManager.GetString("FavoriteCardsEmptyTextBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No favorite links yet!.
        /// </summary>
        public static string FavoriteCardsEmptyTitle {
            get {
                return ResourceManager.GetString("FavoriteCardsEmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer.
        /// </summary>
        public static string FilterClearButton {
            get {
                return ResourceManager.GetString("FilterClearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agence immobilière Chez Papa la commission c’est 2000 balles Confiez-nous votre bien.
        /// </summary>
        public static string FooterAbountCompany {
            get {
                return ResourceManager.GetString("FooterAbountCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Avenue de Suède 06000 Nice.
        /// </summary>
        public static string FooterAddress {
            get {
                return ResourceManager.GetString("FooterAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benefits.
        /// </summary>
        public static string FooterBenefits {
            get {
                return ResourceManager.GetString("FooterBenefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous l&apos;avez compris, nous faisons tout comme une agence immobilière traditionnelle, à un détail près, chez Papa, c&apos;est 2000 balles..
        /// </summary>
        public static string FooterBenefitsText {
            get {
                return ResourceManager.GetString("FooterBenefitsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les Agences De Dapa.
        /// </summary>
        public static string FooterCompanyName {
            get {
                return ResourceManager.GetString("FooterCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string FooterContacts {
            get {
                return ResourceManager.GetString("FooterContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2019 Caspel. Tout droits réservés. Vérsion {0}.
        /// </summary>
        public static string FooterCopyright {
            get {
                return ResourceManager.GetString("FooterCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email: info@lesagencesdepapa.fr.
        /// </summary>
        public static string FooterEmail {
            get {
                return ResourceManager.GetString("FooterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apelle gratuit: --.
        /// </summary>
        public static string FooterPhone {
            get {
                return ResourceManager.GetString("FooterPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom/Prénom:.
        /// </summary>
        public static string FullnameFormLabel {
            get {
                return ResourceManager.GetString("FullnameFormLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom/Prénom:.
        /// </summary>
        public static string FullnameFormPlaceholder {
            get {
                return ResourceManager.GetString("FullnameFormPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string GenderFormLabel {
            get {
                return ResourceManager.GetString("GenderFormLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les Agences De Papa.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inseptions.
        /// </summary>
        public static string Inseptions {
            get {
                return ResourceManager.GetString("Inseptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email invalide.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Apartament.
        /// </summary>
        public static string IsApartmentCheckBox {
            get {
                return ResourceManager.GetString("IsApartmentCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Area.
        /// </summary>
        public static string IsAreaCheckBox {
            get {
                return ResourceManager.GetString("IsAreaCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Bulding.
        /// </summary>
        public static string IsBuildingCheckBox {
            get {
                return ResourceManager.GetString("IsBuildingCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cottage.
        /// </summary>
        public static string IsCottageCheckBox {
            get {
                return ResourceManager.GetString("IsCottageCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Other.
        /// </summary>
        public static string IsOtherCheckBox {
            get {
                return ResourceManager.GetString("IsOtherCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Parking.
        /// </summary>
        public static string IsParkingCheckBox {
            get {
                return ResourceManager.GetString("IsParkingCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telechargement en cours... .
        /// </summary>
        public static string LoadingCardText {
            get {
                return ResourceManager.GetString("LoadingCardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accès client.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accès client.
        /// </summary>
        public static string LoginCardHeader {
            get {
                return ResourceManager.GetString("LoginCardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connectez-vous.
        /// </summary>
        public static string LoginCardTitle {
            get {
                return ResourceManager.GetString("LoginCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page De Connexion.
        /// </summary>
        public static string loginPage {
            get {
                return ResourceManager.GetString("loginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deconnexion.
        /// </summary>
        public static string LogoutButton {
            get {
                return ResourceManager.GetString("LogoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string MapShowPropertyButton {
            get {
                return ResourceManager.GetString("MapShowPropertyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message:.
        /// </summary>
        public static string MessageFormLabel {
            get {
                return ResourceManager.GetString("MessageFormLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to à venir....
        /// </summary>
        public static string PageComeSoon {
            get {
                return ResourceManager.GetString("PageComeSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe:.
        /// </summary>
        public static string PasswordFormLabel {
            get {
                return ResourceManager.GetString("PasswordFormLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 caractère ou plus.
        /// </summary>
        public static string PasswordFormPlaceholder {
            get {
                return ResourceManager.GetString("PasswordFormPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téléphone:.
        /// </summary>
        public static string PhoneFormLabel {
            get {
                return ResourceManager.GetString("PhoneFormLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +XX XXX XXX XX XX.
        /// </summary>
        public static string PhoneFormPlaceholder {
            get {
                return ResourceManager.GetString("PhoneFormPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string ProfileButton {
            get {
                return ResourceManager.GetString("ProfileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenue, {0}.
        /// </summary>
        public static string ProfileCardHeader {
            get {
                return ResourceManager.GetString("ProfileCardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info profil.
        /// </summary>
        public static string ProfileCardTitle {
            get {
                return ResourceManager.GetString("ProfileCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse.
        /// </summary>
        public static string PropertyAddressLabel {
            get {
                return ResourceManager.GetString("PropertyAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chercher l&apos;adresse.
        /// </summary>
        public static string PropertyAddressPlaceHolder {
            get {
                return ResourceManager.GetString("PropertyAddressPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legende.
        /// </summary>
        public static string PropertyCaptionLabel {
            get {
                return ResourceManager.GetString("PropertyCaptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description du bien.
        /// </summary>
        public static string PropertyCaptionPlaceHolder {
            get {
                return ResourceManager.GetString("PropertyCaptionPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string PropertyDescriptionLabel {
            get {
                return ResourceManager.GetString("PropertyDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description détaillée.
        /// </summary>
        public static string PropertyDescriptionPlaceHolder {
            get {
                return ResourceManager.GetString("PropertyDescriptionPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La date ajoutée.
        /// </summary>
        public static string PropertyDetailAddDateLabel {
            get {
                return ResourceManager.GetString("PropertyDetailAddDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info sur l&apos;immeuble.
        /// </summary>
        public static string PropertyDetailBuildingInfoLabel {
            get {
                return ResourceManager.GetString("PropertyDetailBuildingInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre d&apos;etages.
        /// </summary>
        public static string PropertyDetailCardFloorsLabel {
            get {
                return ResourceManager.GetString("PropertyDetailCardFloorsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, superficie totale {1} m².
        /// </summary>
        public static string PropertyDetailCardHeader {
            get {
                return ResourceManager.GetString("PropertyDetailCardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La superficie totale.
        /// </summary>
        public static string PropertyDetailCardSquareLabel {
            get {
                return ResourceManager.GetString("PropertyDetailCardSquareLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} m².
        /// </summary>
        public static string PropertyDetailCardSquareText {
            get {
                return ResourceManager.GetString("PropertyDetailCardSquareText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;état de l&apos;immeuble.
        /// </summary>
        public static string PropertyDetailCardStateLabel {
            get {
                return ResourceManager.GetString("PropertyDetailCardStateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string PropertyDetailDescriptionLabel {
            get {
                return ResourceManager.GetString("PropertyDetailDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carte.
        /// </summary>
        public static string PropertyDetailMapLabel {
            get {
                return ResourceManager.GetString("PropertyDetailMapLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix de vente: .
        /// </summary>
        public static string PropertyDetailSalePriceLabel {
            get {
                return ResourceManager.GetString("PropertyDetailSalePriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les conditions de transaction.
        /// </summary>
        public static string PropertyDetailTransactionTermsLabel {
            get {
                return ResourceManager.GetString("PropertyDetailTransactionTermsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string PropertyImagesLabel {
            get {
                return ResourceManager.GetString("PropertyImagesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string PropertyLatitudeLabel {
            get {
                return ResourceManager.GetString("PropertyLatitudeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string PropertyLongitudeLabel {
            get {
                return ResourceManager.GetString("PropertyLongitudeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placez marqueur sur la carte..
        /// </summary>
        public static string PropertyMapTitleLabel {
            get {
                return ResourceManager.GetString("PropertyMapTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption:.
        /// </summary>
        public static string PropertyNameFormLabel {
            get {
                return ResourceManager.GetString("PropertyNameFormLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déposer un autre.
        /// </summary>
        public static string PropertyNotCloseCheck {
            get {
                return ResourceManager.GetString("PropertyNotCloseCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les Biens De Papa.
        /// </summary>
        public static string PropertyPage {
            get {
                return ResourceManager.GetString("PropertyPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code postal du bien.
        /// </summary>
        public static string PropertyPostalCodeLabel {
            get {
                return ResourceManager.GetString("PropertyPostalCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code postale.
        /// </summary>
        public static string PropertyPostalCodePlaceHolder {
            get {
                return ResourceManager.GetString("PropertyPostalCodePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Région.
        /// </summary>
        public static string PropertyRegionUidLabel {
            get {
                return ResourceManager.GetString("PropertyRegionUidLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer le marqueur.
        /// </summary>
        public static string PropertyResetMarkerLabel {
            get {
                return ResourceManager.GetString("PropertyResetMarkerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix de vente.
        /// </summary>
        public static string PropertySalePriceLabel {
            get {
                return ResourceManager.GetString("PropertySalePriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix de vente en EUR.
        /// </summary>
        public static string PropertySalePricePlaceHolder {
            get {
                return ResourceManager.GetString("PropertySalePricePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bien immobilier.
        /// </summary>
        public static string PropertySectionTitle {
            get {
                return ResourceManager.GetString("PropertySectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvgarder.
        /// </summary>
        public static string PropertySubmitButton {
            get {
                return ResourceManager.GetString("PropertySubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superficie totale.
        /// </summary>
        public static string PropertyTotalSquareLabel {
            get {
                return ResourceManager.GetString("PropertyTotalSquareLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superficie en m².
        /// </summary>
        public static string PropertyTotalSquarePlaceHolder {
            get {
                return ResourceManager.GetString("PropertyTotalSquarePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déposez votre annonce, elle sera traitée par un de nos agents, dites-nous quand est-ce que vous préférez être recontacté.
        /// </summary>
        public static string ProposalAddNewText {
            get {
                return ResourceManager.GetString("ProposalAddNewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programmez votre visite.
        /// </summary>
        public static string ProposalAddNewTitle {
            get {
                return ResourceManager.GetString("ProposalAddNewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse, type du bien (surface, prix net vendeur souhaite etc.).
        /// </summary>
        public static string ProposalAddress {
            get {
                return ResourceManager.GetString("ProposalAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposition.
        /// </summary>
        public static string ProposalCardHeader {
            get {
                return ResourceManager.GetString("ProposalCardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , selectionez le bien et envoyez votre proposition.
        /// </summary>
        public static string ProposalCardsEmptyTextAfter {
            get {
                return ResourceManager.GetString("ProposalCardsEmptyTextAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add proposal- visit .
        /// </summary>
        public static string ProposalCardsEmptyTextBefore {
            get {
                return ResourceManager.GetString("ProposalCardsEmptyTextBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No subscribed proposals yet!.
        /// </summary>
        public static string ProposalCardsEmptyTitle {
            get {
                return ResourceManager.GetString("ProposalCardsEmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refuser.
        /// </summary>
        public static string ProposalDeclineButton {
            get {
                return ResourceManager.GetString("ProposalDeclineButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre mail.
        /// </summary>
        public static string ProposalEmailLabel {
            get {
                return ResourceManager.GetString("ProposalEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom/Prénom:.
        /// </summary>
        public static string ProposalFullNameLabel {
            get {
                return ResourceManager.GetString("ProposalFullNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téléphone:.
        /// </summary>
        public static string ProposalPhoneLabel {
            get {
                return ResourceManager.GetString("ProposalPhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envoyer.
        /// </summary>
        public static string ProposalSaveButton {
            get {
                return ResourceManager.GetString("ProposalSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionnez la date de RDV.
        /// </summary>
        public static string ProposalSelectDateLabel {
            get {
                return ResourceManager.GetString("ProposalSelectDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heures approximatives.
        /// </summary>
        public static string ProposalSelectTimeLabel {
            get {
                return ResourceManager.GetString("ProposalSelectTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualiser le bien.
        /// </summary>
        public static string ProposalShowPropertyButton {
            get {
                return ResourceManager.GetString("ProposalShowPropertyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous recherchez un emploi ou un complément d’activité ? rejoignez les Papas et les Mamans de votre région !.
        /// </summary>
        public static string RecruitementText {
            get {
                return ResourceManager.GetString("RecruitementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recrutement.
        /// </summary>
        public static string Recruitment {
            get {
                return ResourceManager.GetString("Recruitment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV:.
        /// </summary>
        public static string RecruitmentDocument {
            get {
                return ResourceManager.GetString("RecruitmentDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recrutement.
        /// </summary>
        public static string RecruitmentPage {
            get {
                return ResourceManager.GetString("RecruitmentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envoyer.
        /// </summary>
        public static string RecruitmentSaveButton {
            get {
                return ResourceManager.GetString("RecruitmentSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string RecruitmentTitle {
            get {
                return ResourceManager.GetString("RecruitmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Région.
        /// </summary>
        public static string RegionLabel {
            get {
                return ResourceManager.GetString("RegionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom:.
        /// </summary>
        public static string RegionNameFormLabel {
            get {
                return ResourceManager.GetString("RegionNameFormLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Régions.
        /// </summary>
        public static string Regions {
            get {
                return ResourceManager.GetString("Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&apos;inscrire.
        /// </summary>
        public static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&apos;inscire.
        /// </summary>
        public static string RegisterCardHeader {
            get {
                return ResourceManager.GetString("RegisterCardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connectez-vous ou inscrivez-vous.
        /// </summary>
        public static string RegisterCardTitle {
            get {
                return ResourceManager.GetString("RegisterCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La date demandée.
        /// </summary>
        public static string RequestedDateFormLabel {
            get {
                return ResourceManager.GetString("RequestedDateFormLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confiez-nous votre bien immobilier !.
        /// </summary>
        public static string SaleInseptionTitle {
            get {
                return ResourceManager.GetString("SaleInseptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recherche.
        /// </summary>
        public static string SearchButton {
            get {
                return ResourceManager.GetString("SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Search by departament.
        /// </summary>
        public static string SearchByDepartamentLabel {
            get {
                return ResourceManager.GetString("SearchByDepartamentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recherche par mot clé.
        /// </summary>
        public static string SearchByKeywordLabel {
            get {
                return ResourceManager.GetString("SearchByKeywordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entre les mot clés.
        /// </summary>
        public static string SearchByKeywordPlaceholder {
            get {
                return ResourceManager.GetString("SearchByKeywordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recherche par code postale.
        /// </summary>
        public static string SearchByPostalCodeLabel {
            get {
                return ResourceManager.GetString("SearchByPostalCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrer le code postale.
        /// </summary>
        public static string SearchByPostalCodePlaceholder {
            get {
                return ResourceManager.GetString("SearchByPostalCodePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix maximum.
        /// </summary>
        public static string SearchByPriceMaxLabel {
            get {
                return ResourceManager.GetString("SearchByPriceMaxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ Max.
        /// </summary>
        public static string SearchByPriceMaxPlaceholder {
            get {
                return ResourceManager.GetString("SearchByPriceMaxPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix minimum.
        /// </summary>
        public static string SearchByPriceMinLabel {
            get {
                return ResourceManager.GetString("SearchByPriceMinLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ Min.
        /// </summary>
        public static string SearchByPriceMinPlaceholder {
            get {
                return ResourceManager.GetString("SearchByPriceMinPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recherche par région.
        /// </summary>
        public static string SearchByRegionLabel {
            get {
                return ResourceManager.GetString("SearchByRegionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Room Max.
        /// </summary>
        public static string SearchByRoomMaxLabel {
            get {
                return ResourceManager.GetString("SearchByRoomMaxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Max count.
        /// </summary>
        public static string SearchByRoomMaxPlaceholder {
            get {
                return ResourceManager.GetString("SearchByRoomMaxPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Room Min.
        /// </summary>
        public static string SearchByRoomMinLabel {
            get {
                return ResourceManager.GetString("SearchByRoomMinLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Min count.
        /// </summary>
        public static string SearchByRoomMinPlaceholder {
            get {
                return ResourceManager.GetString("SearchByRoomMinPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Square max.
        /// </summary>
        public static string SearchBySquareMaxLabel {
            get {
                return ResourceManager.GetString("SearchBySquareMaxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _m² Max.
        /// </summary>
        public static string SearchBySquareMaxPlaceholder {
            get {
                return ResourceManager.GetString("SearchBySquareMaxPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Square min.
        /// </summary>
        public static string SearchBySquareMinLabel {
            get {
                return ResourceManager.GetString("SearchBySquareMinLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _m² Min.
        /// </summary>
        public static string SearchBySquareMinPlaceholder {
            get {
                return ResourceManager.GetString("SearchBySquareMinPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Résultats de la recherche.
        /// </summary>
        public static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services &amp; Tarifs.
        /// </summary>
        public static string ServicePage {
            get {
                return ResourceManager.GetString("ServicePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se connecter.
        /// </summary>
        public static string SignIN {
            get {
                return ResourceManager.GetString("SignIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype:.
        /// </summary>
        public static string SkypeFormLabel {
            get {
                return ResourceManager.GetString("SkypeFormLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recherche….
        /// </summary>
        public static string StartTypingToSearch {
            get {
                return ResourceManager.GetString("StartTypingToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        public static string StatusFormLabel {
            get {
                return ResourceManager.GetString("StatusFormLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La demande a été acceptée. Vous pouvez maintenant vous connecter à votre compte pour voir le statut de votre demande..
        /// </summary>
        public static string SuccessOperationCanLogin {
            get {
                return ResourceManager.GetString("SuccessOperationCanLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La demande a été acceptée. Maintenant, vous pouvez créer un compte pour voir le statut de la demande.
        /// </summary>
        public static string SuccessOperationCanRegister {
            get {
                return ResourceManager.GetString("SuccessOperationCanRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisateurs.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
